export const videoData = [
  // HOME / coding / general
  {
    id: "w7ejDZ8SWv8",
    category: 0,
    image: "https://img.youtube.com/vi/w7ejDZ8SWv8/hqdefault.jpg",
    title: "React JS Full Course for Beginners",
    channel: "Programming with Mosh",
    views: "5.4M Views",
    time: "3 years ago",
    subscribers: "3.8M Subscribers",
    description: "Complete React course for beginners.",
    profile: "https://i.pravatar.cc/60?img=15",
  },
  {
    id: "PkZNo7MFNFg",
    category: 0,
    image: "https://img.youtube.com/vi/PkZNo7MFNFg/hqdefault.jpg",
    title: "JavaScript Tutorial for Beginners",
    channel: "freeCodeCamp.org",
    views: "23M Views",
    time: "5 years ago",
    subscribers: "10M Subscribers",
    description: "Solid JavaScript foundation from scratch.",
    profile: "https://i.pravatar.cc/60?img=18",
  },
  {
    id: "rfscVS0vtbw",
    category: 0,
    image: "https://img.youtube.com/vi/rfscVS0vtbw/hqdefault.jpg",
    title: "Python Full Course for Beginners",
    channel: "freeCodeCamp.org",
    views: "61M Views",
    time: "4 years ago",
    subscribers: "10M Subscribers",
    description: "Complete Python course with examples.",
    profile: "https://i.pravatar.cc/60?img=18",
  },

  // MUSIC
  {
    id: "Zi_XLOBDo_Y",
    category: 10,
    image: "https://img.youtube.com/vi/Zi_XLOBDo_Y/hqdefault.jpg",
    title: "Michael Jackson - Billie Jean",
    channel: "Michael Jackson",
    views: "1.5B Views",
    time: "13 years ago",
    subscribers: "30M Subscribers",
    description: "Official music video.",
    profile: "https://i.pravatar.cc/60?img=40",
  },
  {
    id: "fJ9rUzIMcZQ",
    category: 10,
    image: "https://img.youtube.com/vi/fJ9rUzIMcZQ/hqdefault.jpg",
    title: "Queen - Bohemian Rhapsody",
    channel: "Queen Official",
    views: "1.8B Views",
    time: "15 years ago",
    subscribers: "18M Subscribers",
    description: "Classic official music video.",
    profile: "https://i.pravatar.cc/60?img=41",
  },
  {
    id: "9bZkp7q19f0",
    category: 10,
    image: "https://img.youtube.com/vi/9bZkp7q19f0/hqdefault.jpg",
    title: "PSY - GANGNAM STYLE",
    channel: "officialpsy",
    views: "5.4B Views",
    time: "11 years ago",
    subscribers: "18M Subscribers",
    description: "One of the most popular music videos ever.",
    profile: "https://i.pravatar.cc/60?img=42",
  },

  // GAMING
  {
    id: "gIPGJQ7cD3A",
    category: 20,
    image: "https://img.youtube.com/vi/gIPGJQ7cD3A/hqdefault.jpg",
    title: "Top 10 Open World Games",
    channel: "Gaming Central",
    views: "850K Views",
    time: "8 months ago",
    subscribers: "980K Subscribers",
    description: "Best open world games you should try.",
    profile: "https://i.pravatar.cc/60?img=30",
  },
  {
    id: "QH2-TGUlwu4",
    category: 20,
    image: "https://img.youtube.com/vi/QH2-TGUlwu4/hqdefault.jpg",
    title: "Best Gaming Meme Video",
    channel: "Internet Fun",
    views: "120M Views",
    time: "14 years ago",
    subscribers: "2M Subscribers",
    description: "Funny internet gaming style content.",
    profile: "https://i.pravatar.cc/60?img=31",
  },
  {
    id: "h11u3vtcpaY",
    category: 20,
    image: "https://img.youtube.com/vi/h11u3vtcpaY/hqdefault.jpg",
    title: "Esports Highlights and Reactions",
    channel: "Arena Play",
    views: "640K Views",
    time: "5 months ago",
    subscribers: "560K Subscribers",
    description: "Best esports plays and reactions.",
    profile: "https://i.pravatar.cc/60?img=32",
  },

  // AUTOMOBILES
  {
    id: "J---aiyznGQ",
    category: 2,
    image: "https://img.youtube.com/vi/J---aiyznGQ/hqdefault.jpg",
    title: "Best Car Reviews This Year",
    channel: "Auto Zone",
    views: "1.1M Views",
    time: "10 months ago",
    subscribers: "1.3M Subscribers",
    description: "Popular car reviews and comparisons.",
    profile: "https://i.pravatar.cc/60?img=44",
  },
  {
    id: "L_jWHffIx5E",
    category: 2,
    image: "https://img.youtube.com/vi/L_jWHffIx5E/hqdefault.jpg",
    title: "Luxury Cars You Need To See",
    channel: "Drive Vision",
    views: "870K Views",
    time: "1 year ago",
    subscribers: "620K Subscribers",
    description: "A look at premium cars and features.",
    profile: "https://i.pravatar.cc/60?img=45",
  },
  {
    id: "M7lc1UVf-VE",
    category: 2,
    image: "https://img.youtube.com/vi/M7lc1UVf-VE/hqdefault.jpg",
    title: "Car Tech and Modern Features",
    channel: "Auto Future",
    views: "430K Views",
    time: "7 months ago",
    subscribers: "510K Subscribers",
    description: "Modern car tech and interior features.",
    profile: "https://i.pravatar.cc/60?img=46",
  },

  // SPORTS
  {
    id: "FZ4i3KX2CW4",
    category: 17,
    image: "https://img.youtube.com/vi/FZ4i3KX2CW4/hqdefault.jpg",
    title: "Football Skills and Goals",
    channel: "Sport Mania",
    views: "1.9M Views",
    time: "11 months ago",
    subscribers: "1.1M Subscribers",
    description: "Amazing football goals and skills.",
    profile: "https://i.pravatar.cc/60?img=33",
  },
  {
    id: "aqz-KE-bpKQ",
    category: 17,
    image: "https://img.youtube.com/vi/aqz-KE-bpKQ/hqdefault.jpg",
    title: "Sports Documentary Highlights",
    channel: "Sports TV",
    views: "760K Views",
    time: "5 months ago",
    subscribers: "860K Subscribers",
    description: "Great sports moments and stories.",
    profile: "https://i.pravatar.cc/60?img=34",
  },
  {
    id: "3fumBcKC6RE",
    category: 17,
    image: "https://img.youtube.com/vi/3fumBcKC6RE/hqdefault.jpg",
    title: "Match Reactions and Best Plays",
    channel: "Goal Arena",
    views: "3.1M Views",
    time: "2 weeks ago",
    subscribers: "2.3M Subscribers",
    description: "Latest highlights and reactions.",
    profile: "https://i.pravatar.cc/60?img=35",
  },

  // ENTERTAINMENT
  {
    id: "e-ORhEE9VVg",
    category: 24,
    image: "https://img.youtube.com/vi/e-ORhEE9VVg/hqdefault.jpg",
    title: "Top Netflix Shows Right Now",
    channel: "Stream Picks",
    views: "670K Views",
    time: "1 month ago",
    subscribers: "420K Subscribers",
    description: "Most watched series right now.",
    profile: "https://i.pravatar.cc/60?img=39",
  },
  {
    id: "ub82Xb1C8os",
    category: 24,
    image: "https://img.youtube.com/vi/ub82Xb1C8os/hqdefault.jpg",
    title: "Top Viral Entertainment Clips",
    channel: "Entertainment Hub",
    views: "990K Views",
    time: "4 months ago",
    subscribers: "700K Subscribers",
    description: "Funny and trending entertainment clips.",
    profile: "https://i.pravatar.cc/60?img=47",
  },
  {
    id: "dQw4w9WgXcQ",
    category: 24,
    image: "https://img.youtube.com/vi/dQw4w9WgXcQ/hqdefault.jpg",
    title: "Classic Viral Entertainment Video",
    channel: "Retro Hits",
    views: "1.4B Views",
    time: "14 years ago",
    subscribers: "5M Subscribers",
    description: "A classic internet favorite.",
    profile: "https://i.pravatar.cc/60?img=48",
  },

  // TECHNOLOGY
  {
    id: "V-_O7nl0Ii0",
    category: 28,
    image: "https://img.youtube.com/vi/V-_O7nl0Ii0/hqdefault.jpg",
    title: "Top AI Tools You Should Know",
    channel: "Tech World",
    views: "980K Views",
    time: "4 months ago",
    subscribers: "1.4M Subscribers",
    description: "Useful AI tools for students and developers.",
    profile: "https://i.pravatar.cc/60?img=36",
  },
  {
    id: "OXGznpKZ_sA",
    category: 28,
    image: "https://img.youtube.com/vi/OXGznpKZ_sA/hqdefault.jpg",
    title: "CSS Tutorial for Beginners",
    channel: "Programming with Mosh",
    views: "4.7M Views",
    time: "4 years ago",
    subscribers: "3.8M Subscribers",
    description: "CSS fundamentals and responsive design.",
    profile: "https://i.pravatar.cc/60?img=15",
  },
  {
    id: "Ke90Tje7VS0",
    category: 28,
    image: "https://img.youtube.com/vi/Ke90Tje7VS0/hqdefault.jpg",
    title: "React Tutorial for Beginners",
    channel: "Programming with Mosh",
    views: "3.2M Views",
    time: "5 years ago",
    subscribers: "3.8M Subscribers",
    description: "React basics explained clearly.",
    profile: "https://i.pravatar.cc/60?img=15",
  },

  // BLOGS
  {
    id: "mU6anWqZJcc",
    category: 22,
    image: "https://img.youtube.com/vi/mU6anWqZJcc/hqdefault.jpg",
    title: "Build and Deploy 3 Modern React Apps",
    channel: "JavaScript Mastery",
    views: "1.1M Views",
    time: "1 year ago",
    subscribers: "1.2M Subscribers",
    description: "Build modern React applications.",
    profile: "https://i.pravatar.cc/60?img=21",
  },
  {
    id: "jS4aFq5-91M",
    category: 22,
    image: "https://img.youtube.com/vi/jS4aFq5-91M/hqdefault.jpg",
    title: "React Hooks Explained",
    channel: "Web Dev Simplified",
    views: "1.7M Views",
    time: "3 years ago",
    subscribers: "1.6M Subscribers",
    description: "Understand hooks with examples.",
    profile: "https://i.pravatar.cc/60?img=25",
  },
  {
    id: "kUMe1FH4CHE",
    category: 22,
    image: "https://img.youtube.com/vi/kUMe1FH4CHE/hqdefault.jpg",
    title: "Learn HTML in 12 Minutes",
    channel: "Jake Wright",
    views: "2.8M Views",
    time: "6 years ago",
    subscribers: "420K Subscribers",
    description: "Learn HTML basics quickly.",
    profile: "https://i.pravatar.cc/60?img=12",
  },

  // NEWS
  {
    id: "Zi_XLOBDo_Y",
    category: 25,
    image: "https://img.youtube.com/vi/Zi_XLOBDo_Y/hqdefault.jpg",
    title: "Global News Roundup",
    channel: "World Update",
    views: "550K Views",
    time: "3 days ago",
    subscribers: "700K Subscribers",
    description: "Main global stories in one place.",
    profile: "https://i.pravatar.cc/60?img=40",
  },
  {
    id: "3fumBcKC6RE",
    category: 25,
    image: "https://img.youtube.com/vi/3fumBcKC6RE/hqdefault.jpg",
    title: "Breaking News and Analysis",
    channel: "Daily Report",
    views: "810K Views",
    time: "6 days ago",
    subscribers: "960K Subscribers",
    description: "Fast breakdown of major events.",
    profile: "https://i.pravatar.cc/60?img=41",
  },
  {
    id: "aqz-KE-bpKQ",
    category: 25,
    image: "https://img.youtube.com/vi/aqz-KE-bpKQ/hqdefault.jpg",
    title: "Weekly World Headlines",
    channel: "News Central",
    views: "430K Views",
    time: "1 week ago",
    subscribers: "390K Subscribers",
    description: "Biggest stories of the week.",
    profile: "https://i.pravatar.cc/60?img=49",
  },
  {
    id: "MsnQ5uepIaE",
    category: 10,
    image: "https://img.youtube.com/vi/MsnQ5uepIaE/hqdefault.jpg",
    title: "Adele - Hello",
    channel: "Adele",
    views: "3.2B Views",
    time: "8 years ago",
    subscribers: "31M Subscribers",
    description: "Official Adele music video.",
    profile: "https://i.pravatar.cc/60?img=50",
  },
  {
    id: "kJQP7kiw5Fk",
    category: 10,
    image: "https://img.youtube.com/vi/kJQP7kiw5Fk/hqdefault.jpg",
    title: "Luis Fonsi - Despacito ft. Daddy Yankee",
    channel: "Luis Fonsi",
    views: "8.5B Views",
    time: "7 years ago",
    subscribers: "35M Subscribers",
    description: "One of the biggest music hits ever.",
    profile: "https://i.pravatar.cc/60?img=51",
  },
  {
    id: "ysz5S6PUM-U",
    category: 28,
    image: "https://img.youtube.com/vi/ysz5S6PUM-U/hqdefault.jpg",
    title: "Docker in 100 Seconds",
    channel: "Fireship",
    views: "2.4M Views",
    time: "2 years ago",
    subscribers: "3.1M Subscribers",
    description: "Quick intro to Docker.",
    profile: "https://i.pravatar.cc/60?img=52",
  },
  {
    id: "3JluqTojuME",
    category: 28,
    image: "https://img.youtube.com/vi/3JluqTojuME/hqdefault.jpg",
    title: "Node.js in 100 Seconds",
    channel: "Fireship",
    views: "1.9M Views",
    time: "2 years ago",
    subscribers: "3.1M Subscribers",
    description: "Fast explanation of Node.js.",
    profile: "https://i.pravatar.cc/60?img=53",
  },
  {
    id: "TlB_eWDSMt4",
    category: 20,
    image: "https://img.youtube.com/vi/TlB_eWDSMt4/hqdefault.jpg",
    title: "Minecraft Speedrun Highlights",
    channel: "Block World",
    views: "920K Views",
    time: "9 months ago",
    subscribers: "780K Subscribers",
    description: "Crazy Minecraft speedrun moments.",
    profile: "https://i.pravatar.cc/60?img=54",
  },
  {
    id: "hTWKbfoikeg",
    category: 24,
    image: "https://img.youtube.com/vi/hTWKbfoikeg/hqdefault.jpg",
    title: "Classic Retro Entertainment Clip",
    channel: "Retro Vault",
    views: "11M Views",
    time: "12 years ago",
    subscribers: "1.1M Subscribers",
    description: "Vintage entertainment classic.",
    profile: "https://i.pravatar.cc/60?img=55",
  },
  {
    id: "C0DPdy98e4c",
    category: 17,
    image: "https://img.youtube.com/vi/C0DPdy98e4c/hqdefault.jpg",
    title: "Top 10 Football Goals",
    channel: "Goal Universe",
    views: "2.2M Views",
    time: "1 year ago",
    subscribers: "1.5M Subscribers",
    description: "Best football goals compilation.",
    profile: "https://i.pravatar.cc/60?img=56",
  },
  {
    id: "ScMzIvxBSi4",
    category: 22,
    image: "https://img.youtube.com/vi/ScMzIvxBSi4/hqdefault.jpg",
    title: "Learn JavaScript in Simple Terms",
    channel: "Code Basics",
    views: "680K Views",
    time: "11 months ago",
    subscribers: "410K Subscribers",
    description: "JavaScript explained simply.",
    profile: "https://i.pravatar.cc/60?img=57",
  },
];
export const shortsData = [
  {
    id: "dQw4w9WgXcQ",
    title: "Classic viral short",
    channel: "Retro Hits",
    views: "12M Views",
  },
  {
    id: "QH2-TGUlwu4",
    title: "Funny meme short",
    channel: "Internet Fun",
    views: "8.5M Views",
  },
  {
    id: "9bZkp7q19f0",
    title: "Popular music short",
    channel: "officialpsy",
    views: "22M Views",
  },
  {
    id: "L_jWHffIx5E",
    title: "Entertainment short clip",
    channel: "Viral Mix",
    views: "4.2M Views",
  },
  {
    id: "e-ORhEE9VVg",
    title: "Trending short moment",
    channel: "Stream Picks",
    views: "3.1M Views",
  },
  {
    id: "Zi_XLOBDo_Y",
    title: "Music throwback short",
    channel: "World Update",
    views: "6.7M Views",
  },
];
